definitions:
  steps:
    - step: &slack-notification
        name: Slack Notification
        script:
          - pipe: atlassian/slack-notify:1.0.1
            variables:
              WEBHOOK_URL: ''
              MESSAGE: '($BITBUCKET_COMMIT) for "$BITBUCKET_BRANCH"'
    - step: &git-secrets-scan
        name: Atlassian Security Secrets Scan
        script:
          - pipe: atlassian/git-secrets-scan:0.5.1

pipelines:
  branches:
    main:
      - step: *git-secrets-scan
    loadtest:
      - step: *git-secrets-scan
  custom:
    deploy-live-kidsloop-dev-api:
      - step: &step-deploy-live-kidsloop-dev-api
          name: "Deploy live.kidsloop.dev"
          image: node:lts
          deployment: live-kidsloop-dev-api
          script:
            - cd packages/edge-api/
            - npm ci
            - ./node_modules/.bin/wrangler publish --env dev
          caches:
            - node
    deploy-live-kidsloop-dev-site:
      - step: &step-deploy-live-kidsloop-dev-site
          name: "Deploy live.kidsloop.dev"
          image: node:lts
          deployment: live-kidsloop-dev-site
          script:
            - cd packages/edge-site/
            - npm ci
            - cp packages/page-stream/dist/report.js packages/edge-site/public/
            - cp packages/page-stream/dist/review.js packages/edge-site/public/
            - npm run build-static
            - ./node_modules/.bin/wrangler publish --env dev
          caches:
            - node
    deploy-live-kidsloop-dev:
      - step: *step-deploy-live-kidsloop-dev-api
      - step: *step-deploy-live-kidsloop-dev-site
