name = "kidsloop-live-edge-api"
type = "javascript"
workers_dev = false
vars = { ENVIRONMENT = "unknown" }

[env.james]
account_id = "a511cc00f4a8396e83a447e33044aaa4"
routes = [
  'live-james.kidsloop.dev/h5p/*',
  'live-james.kidsloop.dev/api/*'
]
zone_id = '867a0bd8cc67b876b85a1571bc31620a'

[env.james.vars]
  # Changes here must be mirrored in cloudflare-env.d.ts
ENVIRONMENT = "dev"
JWKS_URL = "https://kidsloop.cloudflareaccess.com/cdn-cgi/access/certs"
JWKS_ISSUER = "https://kidsloop.cloudflareaccess.com"
JWKS_AUDIENCE = "bb5cf47f145f400f32a5a5c53388f5e28701780b0d93b8b97fbdbd6f66e189fd"

[env.james.durable_objects]
bindings = [
  { name = "room", class_name = "Room" },
]

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"